# ---- Error simulation configuration ----
simulate_errors_enable: false

# Options: speed_noise, omega_noise, speed_omega_noise, all_states
error_type: all_states

# Noise magnitude
error: 0.2
gps_sigma: 0.03
yaw_sigma: 1
phi_sigma: 1

#seed
seed: 50